### ISSUE TITLE
Ground truth vs prediction analyzer fails for segmentation in a certain case

### ISSUE THREAD

**Issue by ddenisenko** [musket-ml/musket_core#16]
Steps:

1. Import Kaggle salt competition dataset.
2. Generate Musket wrappers.
3. Accept the default experiment generation.
4. Change resolution to 224x224.
5. Change number of folds to 3.
6. Launch the experiment and wait till its finished.
7. Launch "Analyze predictions", make sure "Fold select strategy" is set to "ALL" and make sure"export to CSV"  is NOT checked. Make sure "Export ground truth to CSV" is NOT checked too. Generate predictions.
8. Select the only stage, "image_with_mask" vizualizer and "ground_truth_vs_prediction" analyzer.

Result: exception.

**Comment by petrochenko-pavel-a** [comment]
Fix is available in musket_ml 0.496
