### ISSUE TITLE
Export to CSV for all folds at once fails for segmentation

### ISSUE THREAD

**Issue by ddenisenko** [musket-ml/musket_core#17]
Steps:

1. Import Kaggle salt competition dataset.
2. Generate Musket wrappers.
3. Accept the default experiment generation.
4. Change resolution to 224x224.
5. Change number of folds to 3.
6. Launch the experiment and wait till its finished.
7. Launch "Analyze predictions", make sure "Fold select strategy" is set to "ALL" and set "export to CSV" to be checked.

Result: exception

**Comment by petrochenko-pavel-a** [comment]
Hi Denis, this seems to work fine for me, According to the exception that you send by skype yesterday it seems that there is some inconsistency in your prediction cache. So I need this cache to investigate what's happening with the encoder

Thanks in advance,
Pavel

**Comment by petrochenko-pavel-a** [comment]
This seems to be fixed
