### ISSUE TITLE
The absence of ground truth CSV makes CSV prediction viewer to hang.

### ISSUE THREAD

**Issue by ddenisenko** [musket-ml/musket_core#18]
Steps:

1. Import Kaggle salt competition dataset.
2. Generate Musket wrappers.
3. Accept the default experiment generation.
4. Change resolution to 224x224.
5. Change number of folds to 3.
6. Launch the experiment and wait till its finished.
7. Launch "Analyze predictions", make sure "Fold select strategy" is set to "0" and set "export to CSV" to be checked. Make sure "Export ground truth to CSV" is NOT checked. Generate predictions.
8. Close all editors/viewers, open experiment editor again and click on "validation0.0" link in "predictions" section.

Result: nothing happens.
Expected result: prediction viewer is opened.

**Comment by petrochenko-pavel-a** [comment]
Fixed
